[phases.setup]
nixPkgs = ["python310", "gcc", "glibc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python test_conversation_interface.py"

[variables]
PORT = "8500"